---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetescode-aapiserver-builder-service-controller
  namespace: kubernetescode-aapiserver-builder
  labels:
    api: kubernetescode-aapiserver-builder-service
    controller: "true"
spec:
  selector:
    matchLabels:
      api: kubernetescode-aapiserver-builder-service
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: kubernetescode-aapiserver-builder-service
        controller: "true"
    spec:
      serviceAccount: aapiserver
      containers:
      - name: controller
        image: jackyzhangfd/kubernetescode-aaserver-builder:1.0
        imagePullPolicy: Always
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: kubernetescode-aapiserver-builder-service
