---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetescode-aapiserver-builder-service-apiserver-auth-reader
rules:
  - apiGroups:
      - ""
    resourceNames:
      - extension-apiserver-authentication
    resources:
      - configmaps
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","watch","list","create","update","delete","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","watch","list","create","delete","update","patch"]
  - apiGroups: ["provision.mydomain.com"]
    resources: ["provisionrequests","provisionrequests/status"]
    verbs: ["get","watch","list","create", "update","patch"]
  - apiGroups: ["flowcontrol.apiserver.k8s.io"]
    resources: ["prioritylevelconfigurations","flowschemas"]
    verbs: ["get","watch","list"]
  - apiGroups: ["flowcontrol.apiserver.k8s.io"]
    resources: ["flowschemas/status"]
    verbs: ["get","watch","list","create", "update","patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetescode-aapiserver-builder-service-apiserver-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetescode-aapiserver-builder-service-apiserver-auth-reader
subjects:
  - kind: ServiceAccount
    namespace: kubernetescode-aapiserver-builder
    name: aapiserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetescode-aapiserver-builder-service-apiserver-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    namespace: kubernetescode-aapiserver-builder
    name: aapiserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetescode-aapiserver-builder-service-controller
  namespace: default
rules:
  - apiGroups:
      - 'provision.mydomain.com'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - 'configmaps'
      - 'namespaces'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - '*'
    verbs:
      - 'list'
      - 'watch'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetescode-aapiserver-builder-service-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetescode-aapiserver-builder-service-controller
subjects:
  - kind: ServiceAccount
    namespace: kubernetescode-aapiserver-builder
    name: aapiserver
